# Spring Boot 配置文件，用于配置 Spring Boot 项目的配置信息

spring:
  application:
    name: spring-boot-chat-backend  # 项目名称，可以随意填写，没有实际作用，只是用于标识项目

  # MongoDB 数据库配置
  data:
    mongodb:
      username: root
      password: password
      host: localhost                 # MongoDB 服务器地址，如果是远程服务器，需要填写服务器的 IP 地址，此处填写 localhost 是因为 MongoDB 服务运行在本地
      port: 27017
      authentication-database: admin  # 认证数据库

server: # 服务端口，可以在 0-65535 之间任意选择，但是不能选择已经被占用的端口，否则会启动失败，推荐选择 1024 以上的端口，因为 1024 以下的端口是系统保留端口
  port: 12394
